### ISSUE TITLE
Does not work if no style.css

### ISSUE THREAD

**Issue by cibulka** [oleynikd/gulp-wp-file-header#1]
Hello Denis, thanks for a nice plugin!

One of my issues though is that if no `style.css` file is present, plugin does nothing. I think there is a lot of developers (including me), who use style.css only for WP theme recognition process and place their CSS to subfolders of their choice.

What if the plugin created an empty file, if no style.css found, and place the header in there?

Thanks!

**Comment by oleynikd** [comment]
This is obvious one. I'll make changes.
Thanks for pointing!

**Comment by cibulka** [comment]
Any progress on the thing? :)

**Comment by oleynikd** [comment]
As it turns out, this not actually is a Gulp plugin... I've discussed this [here](https://github.com/gulpjs/gulp/issues/1237#issuecomment-138707729)
So I'll rebuild it to be a simple nodejs plugin and will change the API completely.

**Comment by cibulka** [comment]
Awesome, thank you!

**Comment by oleynikd** [comment]
@cibulka I've updated plugin completely as well as description and usage examples. Please take a look and test it...

If you'll find any errors feel free to reopen this issue or create a new one.

Thanks.
